name: Update readme with blog posts
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - run: do-the-thing.sh
      - uses: risadams/update-md-rss@v1.0.4
        with:
          feed_list: https://angelofailla.com/index.xml


    
